apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      serviceAccountName: jenkins-robot
      containers:
        - name: spring
          image: private-8f434a0c-kr1-registry.container.nhncloud.com/every_map_image/everymap
          env:
            - name: TZ
              value: "Asia/Seoul"
          ports:
            - containerPort: 8082
          volumeMounts:
            - mountPath: /logs
              name: logging-volume
      volumes:
        - name: logging-volume
          hostPath:
            path: ~/appLog
            type: Directory
      imagePullSecrets:
        - name: registry-credential
