spring.config.activate.on-profile: prod
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 192.168.0.103
    username: postgres
    password: everyDB


logging.level.root : info
logging:
  logback:
    rollingpolicy:
      total-size-cap: 2GB

  file:
    path: /logs
    name: everymap_log
