spring:
  profiles:
    group:
      "prod": "default, prod"
      "dev": "default, dev"
    default:  prod
  application:
    name: every
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
server:
  port: 8082


---


spring.config.activate.on-profile: default
mybatis:
  mapper-locations: "classpath:mybatis/mapper/**/**.xml"
