spring.config.activate.on-profile: prod
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${postgres}
    password: ${everyDB}


logging.level.root : info
logging:
  logback:
    rollingpolicy:
      total-size-cap: 2GB

  file:
    path: /logs
    name: /logs/everymap.log
