spring:
  profiles:
    group:
      "prod": "default, prod"
      "dev": "default, dev"
    default:  prod
  application:
    name: every
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  ai:
    azure:
      openai:
        api-key: ${SPRING_AI_AZURE_OPENAI_API_KEY}
        endpoint: ${SPRING_AI_AZURE_OPENAI_ENDPOINT}
        chat:
          options:
            deployment-name: ${SPRING_AI_AZURE_OPENAI_DEPLOYMENT_NAME}
            model-name: ${SPRING_AI_AZURE_OPENAI_MODEL_NAME}
app:
  vworld:
    key: ${VWORLD_API_KEY}

server:
  port: 8082



---

spring.config.activate.on-profile: default
mybatis:
  mapper-locations: "classpath:mybatis/mapper/**/**.xml"
