spring.config.activate.on-profile: dev
logging:
  level:
    org.apache.ibatis: DEBUG
    root : debug

spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
