spring:
  profiles:
    group:
      "prod": "default, prod"
      "dev": "default, dev"
    active: dev
  application:
    name: every
server:
  port: 8082


---


spring.config.activate.on-profile: default
mybatis:
  mapper-locations: "classpath:mybatis/mapper/**/**.xml"
